### PR TITLE
Color->Colors

### PR DESCRIPTION
**Pull request by sbromberger**
Migration to Colors.jl.

### CODE REVIEW

**Comment by sbromberger** [comment]
Pkg.test is failing locally with

```
julia> Pkg.test("GraphLayout")
INFO: Computing test dependencies for GraphLayout...
INFO: Installing Cbc v0.1.7
INFO: Installing Clp v0.0.10
INFO: Installing JuMP v0.9.3
INFO: Installing ReverseDiffSparse v0.2.10
INFO: Building Homebrew
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 10 (delta 8), reused 10 (delta 8), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/Homebrew/homebrew
   cb4d17e..6d65e3a  master     -> origin/master
HEAD is now at 6d65e3a pypy: update 2.6.1 bottle.
HEAD is now at c490b44 Merge pull request #61 from staticfloat/staging
INFO: Building Cbc
INFO: Testing GraphLayout
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in require at deprecated.jl:659
 in isinstalled at /Users/seth/.julia/v0.4/Compose/src/Compose.jl:34
 in isinstalled at /Users/seth/.julia/v0.4/Compose/src/Compose.jl:28
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in require at /usr/local/julia-latest/lib/julia/sys.dylib
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in require at /usr/local/julia-latest/lib/julia/sys.dylib
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/Compose/src/Compose.jl, in expression starting on line 131

WARNING: deprecated syntax "Elem(:svg,:g) [" at /Users/seth/.julia/v0.4/Compose/src/patchable.jl:197.
Use "Elem(:svg,:g)[" instead.

WARNING: deprecated syntax "Elem(:svg,:g) [" at /Users/seth/.julia/v0.4/Compose/src/patchable.jl:222.
Use "Elem(:svg,:g)[" instead.
Render a pentagon
  > layout_spring_adj
WARNING: color("#000000") is deprecated, use colorant"#000000" or parse(Colorant, "#000000")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:11
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#AAAAFF") is deprecated, use colorant"#AAAAFF" or parse(Colorant, "#AAAAFF")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:11
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#BBBBBB") is deprecated, use colorant"#BBBBBB" or parse(Colorant, "#BBBBBB")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:11
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#BBBBBB") is deprecated, use colorant"#BBBBBB" or parse(Colorant, "#BBBBBB")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:11
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: [a] concatenation is deprecated; use collect(a) instead
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in oldstyle_vcat_warning at /usr/local/julia-latest/lib/julia/sys.dylib
 in vect at abstractarray.jl:32
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:13
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#000000") is deprecated, use colorant"#000000" or parse(Colorant, "#000000")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:13
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#AAAAFF") is deprecated, use colorant"#AAAAFF" or parse(Colorant, "#AAAAFF")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:13
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#BBBBBB") is deprecated, use colorant"#BBBBBB" or parse(Colorant, "#BBBBBB")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:13
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
WARNING: color("#BBBBBB") is deprecated, use colorant"#BBBBBB" or parse(Colorant, "#BBBBBB")
 in depwarn at /usr/local/julia-latest/lib/julia/sys.dylib
 in color at /Users/seth/.julia/v0.4/Colors/src/parse.jl:145
 in compose_layout_adj at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:75
 in __draw_layout_adj#33__ at /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl:149
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:13
 in context at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl:8
 in facts at /Users/seth/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 6
  > layout_stressmajorize_adj
0 facts verified.
Random graph
  > layout_spring_adj
  > layout_stressmajorize_adj
0 facts verified.
ERROR: LoadError: LoadError: UndefVarError: _ordering_ip not defined
 in layout_tree at /Users/seth/.julia/v0.4/GraphLayout/src/tree.jl:79
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in process_options at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/test/test_tree.jl, in expression starting on line 11
while loading /Users/seth/.julia/v0.4/GraphLayout/test/runtests.jl, in expression starting on line 52
```

I suspect this error is unrelated to this change, though the warnings (via Compose) are likely related to the Colors.jl migration. `_ordering_ip` is in `tree_opt.jl`, perhaps it's a simple issue of availability.

**Comment by IainNZ** [comment]
Yeah I mean I don't know what state master is in, its not certainly ready for release. Use at your own risk!

**Comment by sbromberger** [comment]
Would you be comfortable merging this even though the tests are failing? (Master tests are failing anyway, and this does what it says.)

**Comment by IainNZ** [comment]
Sure yeah

**Comment by sbromberger** [comment]
Thanks. I'll see what I can do about cleaning up the tests. From what I'm seeing, the issue is the `@require JuMP include(joinpath(Pkg.dir("GraphLayout","src","tree_opt.jl")))` that doesn't appear to actually include `tree_opt.jl` in the tests.

**Comment by sbromberger** [comment]
See #13 re: test fixes.

**Pull request merged**
