### PR TITLE
Customizabledrawing

### PR DESCRIPTION
**Pull request by jpfairbanks**
@IainNZ,

I added the ability to customize the colors, fontsize, and arrow length. I like to draw undirected graphs without arrows in either direction. I will probably have another PR to color each item in the drawing separately. But as you said, that will be a bigger modification. This is a small patch that you can easily approve and merge.

If you want to rename any parameters, that is fine by me.

### CODE REVIEW

**Comment by IainNZ** [comment]
Looks really good, I'll try it out. We should probably relax the type on the color arguments because I think that it can be a color from Colors.jl too.

**Comment by IainNZ** [comment]
I'd like to give you commit access, would you be interested? It'd still be good to develop new features in a branch so can review before merging, but you'd be able to e.g. make small tweaks easily.

**Comment by jpfairbanks** [comment]
Yes I would use commit access. I'll branch->PR->discuss->merge. I like types as documentation which sometimes leads to overly constrained methods.

**Comment by IainNZ** [comment]
Yeah me too, I'm definitely in favor of using types liberally. I've noticed in the Compose source that all the colour-accepting methods take e.g. `c::Union(ColorValue, AlphaColorValue, String)`. We could type-alias that as `ComposeColor` and use that as the type parameter?

**Comment by jpfairbanks** [comment]
Compose imports Color.jl which provides the ColorValue and AlphaColorValue types. Since we depend on Compose, we can import those types too. Surprising that these two types don't share and AbstractColorValue parent type.

**Comment by jiahao** [comment]
bump

want

**Comment by IainNZ** [comment]
Will get on this today

**Comment by IainNZ** [comment]
I've loosened up the color arguments as discussed

**Pull request merged**
