### PR TITLE
Hierachical layout

### PR DESCRIPTION
**Pull request by IainNZ**
Based on 
http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=4308636&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D4308636
and
http://cs.brown.edu/~rt/gdhandbook/chapters/hierarchical.pdf

Partial success so far, still more work to do. Drawing needs to be more tightly coupled to the algorithm it seems.

Addresses partially #3 

With "optimal coordinates" commit
Imgur

As of "Add up pass" commit:
Imgur

### CODE REVIEW

**Comment by IainNZ** [comment]
@mlubin @joehuchette @jiahao JuMP-powered optimal line-crossing avoidance!

**Comment by IainNZ** [comment]
@dcjones you've made quite a test case ;)

**Comment by mlubin** [comment]
Integer programming solves everything

**Comment by IainNZ** [comment]
Now with optimal x-coordinates. Can't be bothered messing with heuristics when I've got a perfectly good optimal method. Now just got to work on drawing it sensibly.

**Pull request merged**
